JSON_PATH_PREFIX = '../'
CHIP_CONFIGURATION = 'wlp'
CHIP_NAME = 'max32690'
JSON_FILE_NAME = f'{CHIP_NAME}-{CHIP_CONFIGURATION}.json'
C_CONST_FILE_NAME = 'pins_me18.c'
C_CONST_STRING_PREFIX = 'const mxc_gpio_cfg_t'
C_CONST_VAR_PREFIX = "gpio_cfg_"
C_CONST_PIN_PREFIX = "MXC_GPIO"
CSV_COMPARED_FILE_NAME = f"{CHIP_NAME}_{CHIP_CONFIGURATION}_pins_c.csv"

JSON_FUNC_NAMES = "ABC"
NOT_PRESENT_VALUE = "-"
YES_VALUE = "YES"
NO_VALUE = "NO"

IGNORE_C_CONST_NAME_LIST = ['DISABLE']
